### ISSUE TITLE
Add like button

### ISSUE THREAD

**Issue by uriklar** [uriklar/professor#12]
Open questions:
Do we need a downvote button?
Should like appear from the start? Or maybe after solving some part of the board?

Content:
1. Add the like button on the screen
2. Add likes to data model (number field)
3. Save in local storage which boards I liked
4. Create api endpoint that creates the actual like
5. Show user if he liked a board of not

**Comment by marcosmol204** [comment]
I think we don't need downvote button although I will implement both ( maybe in the future we will want ).
I think it should appear from the start, if you think as well write and I will implement it.

**Comment by uriklar** [comment]
I agree with you about the downvote, we don't need it.. But regarding when to show the like, I think we should start with showing it only after a board was completely solved. That way we get a double indication, that the board is good and that it is solvable. If we see the feature isn't being used we can always make it appear sooner..
I think if we show it from the start people could just like boards without solving anything in them so that doesn't give us a good indication if it's a good board

**Comment by marcosmol204** [comment]
How do you think we need to know if some user like some board?
Right now we haven't auth, so the only way is LocalStorage.
do we need to implement it  right now?

**Comment by uriklar** [comment]
Yeah I think local storage is the way for now. And I defenitly think we need this otherwise users won't understand why their like wasn't applied after refreshing

**Comment by marcosmol204** [comment]
I am not sure I understood the issue. I will try to describe it by points:
1) User complete the board
2) Now he can like the board
3) There is a API call to update the DB 
4) Some value is recorded to the local storage to remember that user X liked board Y

**Comment by uriklar** [comment]
exactly. 
We save a local storage entry for each board. You can get it by using the `getLocalStorage` function.
You can add the like indication to the storage item of the board. It could be something like `liked: true`.
You'll also need to add this to the reducer state. When you load a board the local storage for that board is loaded in the store state, so you should have acces to `board.liked` to know if the board has been liked in next visits to the page.

**Comment by marcosmol204** [comment]
Api router => done
Showing component after completing the board => done

On process:
routing after asking, did you love the board ?
