### ISSUE TITLE
Add option to clear board

### ISSUE THREAD

**Issue by uriklar** [uriklar/professor#17]
Should clear that specific board from local storage

**Comment by shvekyha** [comment]
Hi
I can take this feature as my first feature:) 

Can you give me some motivation for doing this and how to approach it?
The meaning is that the current user will be able to "erase" the answers of the board that he already solved? or partially solved?

**Comment by uriklar** [comment]
Hi @shvekyda. Yes to your question the motivation is to reset a board so you can either start it over again, or show it to someone. It was requested by the users :-) 

Right now the whole layout of the app is pretty sensitive to changes so i'm wondering where the best and easiest place to add it is. 

I'm thinking maybe next to the title:
![image](https://user-images.githubusercontent.com/2545447/116387612-a45fde00-a823-11eb-908d-e08ee9c236fc.png)

We could start with a some kind of a reset icon:
![image](https://user-images.githubusercontent.com/2545447/116387719-c0637f80-a823-11eb-8a5f-28b3f99bbe52.png)

Regarding implementation. This is the way data is stored in the user's local storage:
```
{
   "uriklar-1558":{
      "answers":[
         {
            "categoryId":"4",
            "state":1
         },
         {
            "categoryId":"1",
            "state":0
         }
      ]
   },
   "efrat-5556":{
      "answers":[
         {
            "categoryId":"2",
            "state":1
         },
         {
            "categoryId":"1",
            "state":1
         },
         {
            "categoryId":"4",
            "state":1
         },
         {
            "categoryId":"3",
            "state":1
         }
      ]
   }
}
```

What you'd need to do is overwrite the local storage data, without the key of the board selected for reset (for example efrat-5556). 

Then you can dispatch a HydrateBoard action which will reset the locally saved state for this board. So something like:
```
 dispatch({
          type: Actions.HydrateBoard,
          payload: { answers: [] },
        });
```

**Comment by shvekyha** [comment]
ok great! yes I think next to the board title is also the best place for it, I'll use an icon and maybe a tooltip that explains what it does. Do you think we need a confirmation for doing the action? or it will just bug the user?

As for the HydrateBoard action - are we using it in another scenario that I can take a look? We are using it in order to refresh the UI?

**Comment by uriklar** [comment]
Yes, we use it in Store.tsx. When the user loads the page we hydrate the board with the current local storage. 
A tooltip would be great, I don't the we need any confirmation. If we get complaints of users accidentally resetting we'll consider :) 

You can use https://reach.tech/tooltip/ as a tooltip. I used their dialog component already but each component is installed as a separate package

**Comment by shvekyha** [comment]
OK
I was actually thinking of a simple title attribute on the img tag for the tooltip, but I can take a look at the package you sent.

**Comment by uriklar** [comment]
Yeah that would work too :-)
